name: Claude Issue Comment Response
on:
  issue_comment:
    types: [created]
permissions:
  id-token: write  # Required for OIDC token access
  issues: write    # Required for commenting on issues
  pull-requests: write  # Optional, if Claude interacts with PRs
jobs:
  claude-respond:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: "Respond to comments mentioning '@claude' with relevant assistance or code suggestions."
